# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger: none
pr: none

variables:
  vmImageNameDefault: 'ubuntu-latest'

stages:
  - stage: test
    displayName: test
    jobs:
      - job: test
        displayName: test
        pool:
          vmImage: $(vmImageNameDefault)
        steps:
          - task: Kubernetes@1
            displayName: configMap with literal values
            inputs:
              azureSubscriptionEndpoint: 'PM-subscription-sit'
              azureResourceGroup: 'DDS-Kubernetes'
              kubernetesCluster: 'ddsakstest'
              command: apply
              arguments: -f mhc-aks.yaml
              secretType: generic
              #secretArguments: --from-literal=prova_1="ciao1" --from-literal=prova_2="ciao2"
              #secretName: mysecretkey4
              configMapName: myconfig
              forceUpdateConfigMap: true
              configMapArguments: --from-literal=prova_1="ciao1" --from-literal=prova_2="ciao2"
