spring:
  datasource:
    url: jdbc:postgresql://${DB_SERVER}
    username: ${keyvault.cardMDbUsername}
    password: ${keyvault.cardMDbPassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  application:
    name: Tkm Card Manager ${HOSTNAME:0}
  kafka:
    #https://docs.confluent.io/platform/current/installation/configuration/consumer-configs.html
    listener:
      type: batch
    consumer:
      bootstrap-servers: ${KAFKA_APPENDER_BOOTSTRAP_SERVERS}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true
      max-poll-records: ${KAFKA_MAX_POLL_RECORDS:5}
      auto-offset-reset: ${AUTO_OFFSET_RESET:earliest}
      properties:
        security:
          protocol: ${KAFKA_SECURITY_PROTOCOL:SASL_SSL}
        sasl:
          mechanism: ${KAFKA_SASL_MECHANISM:PLAIN}
        partition:
          assignment:
            strategy: org.apache.kafka.clients.consumer.RoundRobinAssignor
    producer:
      retries: 0
      bootstrap-servers: ${KAFKA_APPENDER_BOOTSTRAP_SERVERS}
      client-id: ${KAFKA_GROUP_ID:}${HOSTNAME:0}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        security:
          protocol: ${KAFKA_SECURITY_PROTOCOL:SASL_SSL}
        sasl:
          mechanism: ${KAFKA_SASL_MECHANISM:PLAIN}
    topics:
      read-queue:
        name: ${KAFKA_READ_QUEUE_TOPIC}
        group-id: ${KAFKA_READ_QUEUE_GROUP}
        client-id: ${KAFKA_READ_QUEUE_GROUP}${HOSTNAME:0}
        concurrency: ${KAFKA_READ_MAX_NUMBER_OF_THREADS:1}
        jaas:
          config:
            producer: ${keyvault.tkmReadTokenParPanProducerSaslJaasConfig}
            consumer: ${keyvault.tkmReadTokenParPanConsumerSaslJaasConfig}
      delete-queue:
        name: ${KAFKA_DELETE_QUEUE_TOPIC}
        group-id: ${KAFKA_DELETE_QUEUE_GROUP}
        client-id: ${KAFKA_DELETE_QUEUE_GROUP}${HOSTNAME:0}
        concurrency: ${KAFKA_DELETE_MAX_NUMBER_OF_THREADS:1}
        jaas:
          config:
            producer: ${keyvault.tkmDeleteCardProducerSaslJaasConfig}
            consumer: ${keyvault.tkmDeleteCardConsumerSaslJaasConfig}
      write-queue:
        name: ${KAFKA_WRITE_QUEUE_TOPIC}
        client-id: ${KAFKA_WRITE_QUEUE_GROUP:}${HOSTNAME:0}
        jaas:
          config:
            producer: ${keyvault.tkmWriteUpdateTokenProducerSaslJaasConfig}
      dlt-queue:
        name: ${KAFKA_DLT_QUEUE_TOPIC}
        group-id: ${KAFKA_DLT_QUEUE_GROUP}
        client-id: ${KAFKA_DLT_QUEUE_GROUP}${HOSTNAME:0}
        concurrency: ${KAFKA_DLT_MAX_NUMBER_OF_THREADS:1}
        max-poll-records: ${KAFKA_DLT_MAX_POLL_RECORDS:${spring.kafka.consumer.max-poll-records}}
        jaas:
          config:
            producer: ${keyvault.tkmDltProducerSaslJaasConfig}
            consumer: ${keyvault.tkmDltSaslJaasConfig}
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${CONTEXT_PATH:/}

logging:
  level:
    root: ${LOGGING_LEVEL:INFO}
    org:
      hibernate:
        SQL: ${LOGGING_LEVEL_HIBERNATE:${logging.level.root}}
        type:
          descriptor:
            sql:
              BasicBinder: ${LOGGING_LEVEL_HIBERNATE:${logging.level.root}}
    reactor:
      netty:
        resources: ${NETTY_LOGGING_LEVEL:${logging.level.root}}
  pattern:
    level: "${LOGGING_PATTERN:%p [${spring.application.name}][%X{traceId}|%X{spanId}]}"
azure:
  keyvault:
    enabled: true
    client-id: ${AZURE_KEYVAULT_CLIENT_ID}
    client-key: ${AZURE_KEYVAULT_CLIENT_KEY}
    tenant-id: ${AZURE_KEYVAULT_TENANT_ID}
    uri: ${AZURE_KEYVAULT_URI}
    refresh-interval: 86400000 #24H

keyvault:
  eventhubLogSaslJaasConfig: ${${AZURE_KEYVAULT_PROFILE:prod}-eventhubLogSaslJaasConfig:}
  tkmReadTokenParPanConsumerSaslJaasConfig: ${${AZURE_KEYVAULT_PROFILE:prod}-tkmReadTokenParPanConsumerSaslJaasConfig:}
  tkmWriteUpdateTokenProducerSaslJaasConfig: ${${AZURE_KEYVAULT_PROFILE:prod}-tkmWriteUpdateTokenProducerSaslJaasConfig:}
  tkmDeleteCardConsumerSaslJaasConfig: ${${AZURE_KEYVAULT_PROFILE:prod}-tkmDeleteCardConsumerSaslJaasConfig:}
  tkmReadTokenParPanPvtPgpKey: ${${AZURE_KEYVAULT_PROFILE:prod}-tkmReadTokenParPanPvtPgpKey}
  tkmReadTokenParPanPvtPgpKeyPassphrase: ${${AZURE_KEYVAULT_PROFILE:prod}-tkmReadTokenParPanPvtPgpKeyPassphrase:}
  cardMDbUsername: ${${AZURE_KEYVAULT_PROFILE:prod}-cardMDbUsername}
  cardMDbPassword: ${${AZURE_KEYVAULT_PROFILE:prod}-cardMDbPassword}
  apimSubscriptionTkmRtd: ${${AZURE_KEYVAULT_PROFILE:prod}-apimSubscriptionTkmRtd}
  cryptographicKeyId: ${AZURE_KEYVAULT_PROFILE:prod}-pan-token-rsa-key
  tkmReadTokenParPanProducerSaslJaasConfig:  ${${AZURE_KEYVAULT_PROFILE:prod}-tkmReadTokenParPanProducerSaslJaasConfig:}
  tkmDeleteCardProducerSaslJaasConfig: ${${AZURE_KEYVAULT_PROFILE:prod}-tkmDeleteCardProducerSaslJaasConfig:}
  tkmDltProducerSaslJaasConfig: ${${AZURE_KEYVAULT_PROFILE:prod}-tkmDltProducerSaslJaasConfig:}
  tkmDltSaslJaasConfig: ${${AZURE_KEYVAULT_PROFILE:prod}-tkmDltSaslJaasConfig:}

client-urls:
  consent-manager: ${CONSENT_MANAGER_URL}
  rtd-hashing-url: ${RTD_HASHING_URL}

management:
  endpoints:
    web:
      exposure:
        include: "info,health,prometheus"

batch:
  kafka-dlt-read:
    cron: ${KAFKA_DLT_READ_CRON:-}