DB_SERVER: localhost:5000/tkm_card_manager
SERVER_PORT: 8745
ENABLE_KAFKA_APPENDER: FALSE
RTD_HASHING_URL: http://localhost:8741/mock/hash/evaluate
CONSENT_MANAGER_URL: http://localhost:8744
KAFKA_APPENDER_BOOTSTRAP_SERVERS: localhost:9092
KAFKA_SECURITY_PROTOCOL: PLAINTEXT
KAFKA_APPENDER_SECURITY_PROTOCOL: PLAINTEXT
KAFKA_APPENDER_TOPIC: tkm-log
KAFKA_WRITE_QUEUE_TOPIC: tkm-write-update-token
KAFKA_DELETE_QUEUE_TOPIC: tkm-delete-card
KAFKA_DELETE_QUEUE_GROUP: tkm-delete-group
KAFKA_READ_QUEUE_TOPIC: tkm-read-token-par-pan
KAFKA_READ_QUEUE_GROUP: tkm-read-group
AZURE_KEYVAULT_PROFILE: local

## NEED SET
AZURE_KEYVAULT_URI: ${AZURE_KEYVAULT_URI}
AZURE_KEYVAULT_CLIENT_ID: ${AZURE_KEYVAULT_CLIENT_ID}
AZURE_KEYVAULT_CLIENT_KEY: ${AZURE_KEYVAULT_CLIENT_ID}
AZURE_KEYVAULT_TENANT_ID: ${AZURE_KEYVAULT_CLIENT_ID}
