spring:
  datasource:
    url: jdbc:postgresql://${DB_SERVER}
    username: ${keyvault.cardMDbUsername}
    password: ${keyvault.cardMDbPassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: Tkm Card Manager ${HOSTNAME:0}
  kafka:
    consumer:
      retries: 0
      bootstrap-servers: ${KAFKA_SERVERS}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true
      properties:
        security:
          protocol: ${KAFKA_SECURITY_PROTOCOL:SASL_SSL}
        sasl:
          mechanism: ${KAFKA_SASL_MECHANISM:PLAIN}
    producer:
      bootstrap-servers: ${KAFKA_SERVERS}
      client-id: ${KAFKA_GROUP_ID:}${HOSTNAME:0}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        security:
          protocol: ${KAFKA_SECURITY_PROTOCOL:SASL_SSL}
        sasl:
          mechanism: ${KAFKA_SASL_MECHANISM:PLAIN}
          jaas:
            config: ${keyvault.tkmWriteUpdateTokenProducerSaslJaasConfig}
    topics:
      read-queue:
        name: ${KAFKA_READ_QUEUE_TOPIC}
        group-id: ${KAFKA_READ_QUEUE_GROUP}
        client-id: ${KAFKA_READ_QUEUE_GROUP}${HOSTNAME:0}
        concurrency: ${KAFKA_READ_MAX_NUMBER_OF_THREADS:1}
      write-queue: ${KAFKA_WRITE_QUEUE_TOPIC}
      delete-queue:
        name: ${KAFKA_DELETE_QUEUE_TOPIC}
        group-id: ${KAFKA_DELETE_QUEUE_GROUP}
        client-id: ${KAFKA_DELETE_QUEUE_GROUP}${HOSTNAME:0}
        concurrency: ${KAFKA_DELETE_MAX_NUMBER_OF_THREADS:1}

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${CONTEXT_PATH:/}

logging:
  level:
    root: ${LOGGING_LEVEL:INFO}
    org:
      hibernate:
        SQL: ${LOGGING_LEVEL_HIBERNATE:INFO}
        type:
          descriptor:
            sql:
              BasicBinder: ${LOGGING_LEVEL_HIBERNATE:INFO}
  pattern:
    level: "${LOGGING_PATTERN:%p [${spring.application.name}][%X{traceId}|%X{spanId}]}"
azure:
  keyvault:
    enabled: true
    client-id: ${AZURE_KEYVAULT_CLIENT_ID}
    client-key: ${AZURE_KEYVAULT_CLIENT_KEY}
    tenant-id: ${AZURE_KEYVAULT_TENANT_ID}
    uri: ${AZURE_KEYVAULT_URI}

keyvault:
  eventhubLogSaslJaasConfig: ${${AZURE_KEYVAULT_PROFILE:prod}-eventhubLogSaslJaasConfig:}
  tkmReadTokenParPanConsumerSaslJaasConfig: ${${AZURE_KEYVAULT_PROFILE:prod}-tkmReadTokenParPanConsumerSaslJaasConfig:}
  tkmWriteUpdateTokenProducerSaslJaasConfig: ${${AZURE_KEYVAULT_PROFILE:prod}-tkmWriteUpdateTokenProducerSaslJaasConfig:}
  tkmDeleteCardConsumerSaslJaasConfig: ${${AZURE_KEYVAULT_PROFILE:prod}-tkmDeleteCardConsumerSaslJaasConfig:}
  tkmReadTokenParPanPvtPgpKey: ${${AZURE_KEYVAULT_PROFILE:prod}-tkmReadTokenParPanPvtPgpKey}
  tkmReadTokenParPanPvtPgpKeyPassphrase: ${${AZURE_KEYVAULT_PROFILE:prod}-tkmReadTokenParPanPvtPgpKeyPassphrase:}
  cardMDbUsername: ${${AZURE_KEYVAULT_PROFILE:prod}-cardMDbUsername}
  cardMDbPassword: ${${AZURE_KEYVAULT_PROFILE:prod}-cardMDbPassword}
  apimSubscriptionTkmRtd: ${${AZURE_KEYVAULT_PROFILE:prod}-apimSubscriptionTkmRtd}
  cryptographicKeyId: ${AZURE_KEYVAULT_PROFILE:prod}-pan-token-rsa-key

client-urls:
  consent-manager: ${CONSENT_MANAGER_URL}
  rtd-hashing-url: ${RTD_HASHING_URL}

management:
  endpoints:
    web:
      exposure:
        include: "info,health,prometheus"