CREATE TABLE CARD (
ID SERIAL PRIMARY KEY,
PAN VARCHAR(500),
HPAN VARCHAR(64),
PAR VARCHAR(32),
CIRCUIT VARCHAR(32) NOT NULL,
CREATION_DATE TIMESTAMP not null,
LAST_UPDATE_DATE TIMESTAMP,
LAST_READ_DATE TIMESTAMP
);
ALTER TABLE CARD ADD CONSTRAINT UQ_HPAN_PAR UNIQUE(HPAN, PAR);
ALTER TABLE CARD ADD CONSTRAINT hpan_un UNIQUE (HPAN);
ALTER TABLE CARD ADD CONSTRAINT par_un UNIQUE (PAR);

CREATE TABLE CARD_TOKEN (
ID SERIAL PRIMARY KEY,
CARD_ID INT NOT NULL,
TOKEN VARCHAR(500) NOT NULL,
HTOKEN VARCHAR(64) NOT NULL,
CREATION_DATE TIMESTAMP not null,
LAST_UPDATE_DATE TIMESTAMP,
LAST_READ_DATE TIMESTAMP,
DELETED BOOLEAN NOT NULL DEFAULT FALSE,
CONSTRAINT FK_TOKEN FOREIGN KEY(CARD_ID) REFERENCES CARD(ID)
);
CREATE UNIQUE INDEX ON CARD_TOKEN(HTOKEN) WHERE NOT DELETED;

CREATE TABLE CITIZEN (
ID SERIAL PRIMARY KEY,
TAX_CODE VARCHAR(16) NOT NULL,
DELETED BOOLEAN NOT NULL DEFAULT FALSE,
CREATION_DATE TIMESTAMP not NULL
);

CREATE UNIQUE INDEX ON CITIZEN(TAX_CODE) WHERE NOT DELETED;

CREATE TABLE CITIZEN_CARD (
ID SERIAL PRIMARY KEY,
CITIZEN_ID INT NOT NULL,
CARD_ID INT NOT NULL,
CREATION_DATE TIMESTAMP not NULL,
LAST_UPDATE_DATE TIMESTAMP,
DELETED BOOLEAN NOT NULL DEFAULT FALSE,
CONSTRAINT FK_CITIZEN FOREIGN KEY(CITIZEN_ID) REFERENCES CITIZEN(ID),
CONSTRAINT FK_CARD FOREIGN KEY(CARD_ID) REFERENCES CARD(ID)
);

CREATE UNIQUE INDEX ON CITIZEN_CARD(CITIZEN_ID,CARD_ID) WHERE NOT DELETED;

CREATE TABLE BATCH_RESULT (
ID SERIAL PRIMARY KEY,
TARGET_BATCH VARCHAR(32) NOT NULL,
RUN_DATE TIMESTAMP NOT NULL,
RUN_OUTCOME BOOL NOT NULL,
DETAILS VARCHAR(10000) NOT NULL,
RUN_DURATION_MILLIS INT4 NOT NULL,
EXECUTION_TRACE_ID VARCHAR(16) NOT NULL,
EXECUTED_BY VARCHAR(100)  NULL
);